/**
 * Domain types returned by the {@link POLITEShop} client. These are plain
 * TypeScript interfaces, independent of any ORM or database schema.
 */

// ── User & Organization ───────────────────────────────────────────────────────

export interface User {
  id: string;
  name: string;
}

export interface Institution {
  id: string;
  name: string;
}

// ── Semesters & Modules ───────────────────────────────────────────────────────

export interface Semester {
  id: string;
  name: string;
}

export interface Module {
  id: string;
  name: string;
  code: string;
}

// ── Content ───────────────────────────────────────────────────────────────────

export interface ActivityFolder {
  type: "folder";
  id: string;
  name: string;
  description: string;
  sortOrder: number;
  contents: (AnyActivity | ActivityFolder)[];
}

// ── Activities ────────────────────────────────────────────────────────────────

interface BaseActivity {
  id: string;
  sortOrder: number;
}

export interface HTMLActivity extends BaseActivity {
  type: "html";
  name: string;
  /** Raw HTML content of the activity page. */
  content: string;
}

export interface WebEmbedActivity extends BaseActivity {
  type: "web_embed";
  name: string;
  /** The URL to embed in an iframe. */
  url: string;
}

export interface DocEmbedActivity extends BaseActivity {
  type: "doc_embed";
  name: string;
  /** Original source file URL (e.g. .pptx, .docx, .pdf). */
  sourceURL: string;
  /** URL of a browser-renderable PDF preview generated by Brightspace, if available. */
  previewURL?: string;
  /** Expiry date of the preview URL, if it is time-limited. */
  previewURLExpiry?: Date;
}

export interface VideoEmbedActivity extends BaseActivity {
  type: "video_embed";
  name: string;
  /** Signed URL of the video file hosted on Brightspace Content Service / S3. */
  sourceURL: string;
  /** Expiry date of the source URL. */
  sourceURLExpiry?: Date;
  /** Signed URL of the video thumbnail. */
  thumbnailURL: string;
  /** Expiry date of the thumbnail URL. */
  thumbnailURLExpiry?: Date;
}

export interface SubmissionActivity extends BaseActivity {
  type: "submission";
  /** ID of the dropbox folder this activity links to. */
  dropboxId: string;
}

export interface QuizActivity extends BaseActivity {
  type: "quiz";
  /** ID of the quiz this activity links to. */
  quizId: string;
}

export interface UnknownActivity extends BaseActivity {
  type: "unknown";
}

export type AnyActivity =
  | HTMLActivity
  | WebEmbedActivity
  | DocEmbedActivity
  | VideoEmbedActivity
  | SubmissionActivity
  | QuizActivity
  | UnknownActivity;

// ── Dropboxes & Submissions ───────────────────────────────────────────────────

export interface SubmissionDropbox {
  id: string;
  name: string;
  moduleId: string;
  description: string;
  dueAt: Date | null;
  opensAt?: Date | null;
  closesAt?: Date | null;
}

export interface Submission {
  id: string;
  dropboxId: string;
  submittedAt: Date | null;
  comment?: string;
}

// ── Quizzes ───────────────────────────────────────────────────────────────────

export interface Quiz {
  id: string;
  moduleId: string;
  name: string;
  description: string;
  dueAt: Date | null;
}
