openapi: 3.0.0
info:
  title: Brightspace Content Service
  version: 1.0.0
  description: |
    API for the `content-service.api.brightspace.com` subdomain, used by the POLITEMall client.
    This is a hypermedia API that uses the Siren format for managing video content and thumbnails.
servers:
  - url: "https://{tenantId}.content-service.api.brightspace.com"
    variables:
      tenantId:
        default: "746e9230-82d6-4d6b-bd68-5aa40aa19cce"
        description: "The ID of the Brightspace tenant (e.g., 746e9230-82d6-4d6b-bd68-5aa40aa19cce)."
tags:
  - name: Content
    description: Operations related to content topics and media.
paths:
  /topics/{moduleId}/{activityId}:
    get:
      summary: Get topic thumbnail
      tags:
        - Content
      description: |
        Fetches thumbnail information for a content topic.
        Used for ContentService activities (typically videos).
      operationId: getTopicThumbnail
      security:
        - brightspaceJWT: []
      parameters:
        - name: moduleId
          in: path
          required: true
          description: The ID of the module.
          schema:
            type: string
            example: "51409"
        - name: activityId
          in: path
          required: true
          description: The ID of the activity (topic).
          schema:
            type: string
            example: "4349549"
      responses:
        "200":
          description: "A Siren entity containing thumbnail information."
          content:
            application/json:
              schema:
                $ref: "../shared/siren.yaml#/components/schemas/ContentServiceTopicEntity"
              example:
                class:
                  - "topic"
                  - "content-service"
                entities:
                  - class:
                      - "thumbnail"
                    rel:
                      - "item"
                    properties:
                      src: "https://content-service.brightspace.com/thumbnail.jpg"
                      expires: 1771343317
                links:
                  - rel:
                      - "self"
                    href: "https://746e9230-82d6-4d6b-bd68-5aa40aa19cce.content-service.api.brightspace.com/topics/51409/4349549"
        "403":
          description: "Forbidden. The JWT is likely invalid or expired."

  /topics/{moduleId}/{activityId}/media:
    get:
      summary: Get topic media
      tags:
        - Content
      description: |
        Fetches media information for a content topic, typically a video.
        Returns URLs that may be time-limited (check expires property).
      operationId: getTopicMedia
      security:
        - brightspaceJWT: []
      parameters:
        - name: moduleId
          in: path
          required: true
          description: The ID of the module.
          schema:
            type: string
            example: "51409"
        - name: activityId
          in: path
          required: true
          description: The ID of the activity (topic).
          schema:
            type: string
            example: "4349549"
      responses:
        "200":
          description: "A Siren entity containing information about the media."
          content:
            application/json:
              schema:
                $ref: "../shared/siren.yaml#/components/schemas/ContentServiceMediaEntity"
              example:
                class:
                  - "video"
                properties:
                  src: "https://content-service.brightspace.com/video.mp4"
                  expires: 1771343317
                links:
                  - rel:
                      - "self"
                    href: "https://746e9230-82d6-4d6b-bd68-5aa40aa19cce.content-service.api.brightspace.com/topics/51409/4349549/media"
        "403":
          description: "Forbidden. The JWT is likely invalid or expired."

components:
  securitySchemes:
    brightspaceJWT:
      $ref: "shared/components.yaml#/components/securitySchemes/brightspaceJWT"
