openapi: 3.0.0
info:
  title: Brightspace Enrollments
  version: 1.0.0
  description: |
    API for the `enrollments.api.brightspace.com` subdomain, used by the POLITEMall client.
    This is a hypermedia API that uses the Siren format.
servers:
  - url: "https://{tenantId}.enrollments.api.brightspace.com"
    variables:
      tenantId:
        default: "746e9230-82d6-4d6b-bd68-5aa40aa19cce"
        description: "The ID of the Brightspace tenant (e.g., 746e9230-82d6-4d6b-bd68-5aa40aa19cce)."
tags:
  - name: Enrollments
    description: Operations related to user course enrollments.
paths:
  /users/{userId}:
    get:
      summary: Get user enrollments
      tags:
        - Enrollments
      description: Fetches the list of a user's course enrollments in Siren format.
      operationId: getUserEnrollments
      security:
        - brightspaceJWT: []
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user.
          schema:
            type: string
            example: "490586"
        - name: pageSize
          in: query
          description: "The number of results to return per page."
          schema:
            type: integer
            default: 100
      responses:
        "200":
          description: "A Siren entity representing the user's enrollments."
          content:
            application/json:
              schema:
                $ref: "../shared/siren.yaml#/components/schemas/UserEnrollmentsEntity"
              example:
                class:
                  - "enrollments"
                  - "collection"
                entities:
                  - class:
                      - "enrollment"
                      - "unpinned"
                    rel:
                      - "item"
                    entities:
                      - class:
                          - "course-offering"
                        rel:
                          - "https://api.brightspace.com/rels/organization"
                        properties:
                          name: "Personalised Learning Pathway (PLP)"
                          code: "22S1-IS_PLP_NP"
                          homepageUrl: "https://nplms.polite.edu.sg/d2l/home/51409"
                        links:
                          - rel:
                              - "self"
                            href: "https://746e9230-82d6-4d6b-bd68-5aa40aa19cce.organizations.api.brightspace.com/51409"
                          - rel:
                              - "https://api.brightspace.com/rels/course-image"
                            href: "https://746e9230-82d6-4d6b-bd68-5aa40aa19cce.organizations.api.brightspace.com/51409/image"
                      - class:
                          - "semester"
                        rel:
                          - "https://api.brightspace.com/rels/semester"
                        properties:
                          name: " Non-Term"
                          code: "ADHOC"
                        links:
                          - rel:
                              - "self"
                            href: "https://746e9230-82d6-4d6b-bd68-5aa40aa19cce.organizations.api.brightspace.com/67189"
                    links:
                      - rel:
                          - "self"
                        href: "https://746e9230-82d6-4d6b-bd68-5aa40aa19cce.enrollments.api.brightspace.com/users/490586/enrollments/51409"
                      - rel:
                          - "https://api.brightspace.com/rels/user"
                        href: "https://746e9230-82d6-4d6b-bd68-5aa40aa19cce.users.api.brightspace.com/490586"
                links:
                  - rel:
                      - "self"
                    href: "https://746e9230-82d6-4d6b-bd68-5aa40aa19cce.enrollments.api.brightspace.com/users/490586"
                  - rel:
                      - "https://api.brightspace.com/rels/user"
                    href: "https://746e9230-82d6-4d6b-bd68-5aa40aa19cce.users.api.brightspace.com/490586"
        "403":
          description: "Forbidden. The JWT is likely invalid or expired."

components:
  securitySchemes:
    brightspaceJWT:
      $ref: "shared/components.yaml#/components/securitySchemes/brightspaceJWT"
